name: new_env
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.4.4=pyhd8ed1ab_1
  - aiohttp=3.11.10=py39h9399b63_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alabaster=0.7.16=py39h06a4308_0
  - aom=3.5.0=h27087fc_0
  - arrow=1.2.3=py39h06a4308_1
  - astroid=2.14.2=py39h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - asyncssh=2.17.0=py39h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=23.1.0=py39h06a4308_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.8.0=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.14=hbcca054_0
  - certifi=2024.12.14=py39h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_0
  - chardet=4.0.0=py39h06a4308_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - cloudpickle=3.0.0=py39h06a4308_0
  - colorama=0.4.6=py39h06a4308_0
  - comm=0.2.1=py39h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cookiecutter=2.6.0=py39h06a4308_0
  - cryptography=43.0.0=py39hdda0065_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - curl=8.9.1=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py39h06a4308_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.8=py39h06a4308_0
  - docstring-to-markdown=0.11=py39h06a4308_0
  - docutils=0.18.1=py39h06a4308_3
  - double-conversion=3.2.0=h27087fc_1
  - eigen=3.4.0=hdb19cb5_0
  - elfutils=0.189=hde5d1a3_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.13.1=py39h06a4308_0
  - flake8=7.0.0=py39h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.5.0=py39h8cd3c5a_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gl2ps=1.4.2=h0708190_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.7.9=hb077bed_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - imageio=2.33.1=py39h06a4308_0
  - imagesize=1.4.1=py39h06a4308_0
  - importlib-metadata=7.0.1=py39h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - inflection=0.5.1=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.29.5=py39h06a4308_0
  - ipython=8.15.0=py39h06a4308_0
  - isort=5.13.2=py39h06a4308_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py39h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=1.0.1=py39hb02cf49_0
  - jinja2=3.1.4=py39h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsoncpp=1.9.5=h4bd325d_1
  - jsonschema=4.23.0=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - jupyterlab_pygments=0.2.2=py39h06a4308_0
  - keyring=24.3.1=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - lazy-object-proxy=1.10.0=py39h5eee18b_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.6.2=h3d51595_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.7=hd590300_0
  - libitk=5.3.0=hcedbc38_0
  - libllvm14=14.0.6=hecde1de_4
  - libllvm17=17.0.6=hc9c083f_1
  - libmicrohttpd=0.9.77=h97afed2_0
  - libnetcdf=4.8.1=nompi_h261ec11_106
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libogg=1.3.5=h4ab18f5_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py39h6a678d5_0
  - loguru=0.7.2=py39hf3d152e_2
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=hd590300_1001
  - markdown-it-py=2.2.0=py39h06a4308_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.9.2=py39h06a4308_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py39h06a4308_0
  - mesalib=23.3.2=h6b56f8e_0
  - mistune=2.0.4=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h5eee18b_0
  - mkl_random=1.2.7=py39h1128e8f_0
  - more-itertools=10.3.0=py39h06a4308_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - msgpack-python=1.1.0=py39h74842e3_0
  - multidict=6.1.0=py39h9399b63_2
  - mypy_extensions=1.0.0=py39h06a4308_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py39h06a4308_0
  - nbconvert=7.16.4=py39h06a4308_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=py39h06a4308_0
  - nlohmann_json=3.11.3=he02047a_1
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.60.0=py39h0320e7d_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - numpydoc=1.7.0=py39h06a4308_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.4.0=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=py39h06a4308_0
  - pandas=2.2.2=py39h6a678d5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - plotly=5.24.1=py_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.1.0=h93bde94_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - propcache=0.2.1=py39h8cd3c5a_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.11.4=h59595ed_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycodestyle=2.11.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py39h06a4308_0
  - pyflakes=3.2.0=py39h06a4308_0
  - pygithub=2.4.0=py39h06a4308_0
  - pygments=2.15.1=py39h06a4308_1
  - pyjwt=2.9.0=py39h06a4308_0
  - pykrige=1.7.2=py39hd92a3bb_1
  - pylint=2.16.2=py39h06a4308_0
  - pylint-venv=3.0.3=py39h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py39h5eee18b_0
  - pyparsing=3.1.2=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pyqtwebengine=5.15.10=py39h6a678d5_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-lsp-black=2.0.0=py39h06a4308_0
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.10.0=py39h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.6=py39h06a4308_0
  - pytorch=2.5.1=py3.9_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - pyuca=1.2=py39h06a4308_1
  - pyvista=0.42.0=pyhd8ed1ab_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py39h06a4308_0
  - qt-main=5.15.2=h53bd1ea_10
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtawesome=1.3.1=py39h06a4308_0
  - qtconsole=5.5.1=py39h06a4308_0
  - qtpy=2.4.1=py39h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.32.3=py39h06a4308_0
  - rich=13.7.1=py39h06a4308_0
  - rope=1.12.0=py39h06a4308_0
  - rpds-py=0.10.6=py39hb02cf49_0
  - rtree=1.0.1=py39h06a4308_0
  - scikit-gstat=1.0.19=py39hf3d152e_0
  - scikit-learn=1.5.1=py39h1128e8f_0
  - scipy=1.13.1=py39h5f9d8c6_0
  - scooby=0.10.0=pyhd8ed1ab_1
  - seaborn=0.13.2=py39h06a4308_0
  - secretstorage=3.3.1=py39h06a4308_1
  - setuptools=75.1.0=py39h06a4308_0
  - simpleitk=2.2.1=py39hdaa313e_1
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py39h06a4308_0
  - sphinx=7.3.7=py39h5eee18b_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.10=py39h06a4308_0
  - spyder=5.5.1=py39h06a4308_4
  - spyder-kernels=2.5.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - superqt=0.6.7=py39h2f386ee_0
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.13.2=py39h06a4308_0
  - tabulate=0.9.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - tenacity=9.0.0=py39h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - torchtriton=3.1.0=py39
  - torchvision=0.15.2=cpu_py39h83e0c9b_0
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.66.5=py39h2f386ee_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - ujson=5.10.0=py39h6a678d5_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - unidecode=1.3.8=py39h06a4308_0
  - urllib3=2.2.3=py39h06a4308_0
  - utfcpp=4.0.6=h005c6e1_0
  - vtk=9.2.5=osmesa_py39hd200a8d_100
  - watchdog=4.0.1=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - whatthepatch=1.0.2=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - wrapt=1.14.1=py39h5eee18b_0
  - wslink=2.2.1=pyhd8ed1ab_1
  - wurlitzer=3.0.2=py39h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-glproto=1.4.17=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.40.2=py39h06a4308_0
  - yarl=1.18.3=py39h8cd3c5a_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - dijkstra3d==1.15.1
      - h5py==3.12.1
      - hdf5storage==0.1.19
prefix: /home/gabriel/anaconda3/envs/meu_ambiente
